apiVersion: apps/v1
kind: Deployment
metadata:
  name: { {  include "polybot.fullname" . } }
  labels:
    app: { {  include "polybot.name" . } }
spec:
 replicas:  { {  .values.replicaCount } }
 selector:
   matchLabels:
     app:  { {  include "polybot.name" . } }

 template:
   metadata:
     labels:
       app:  { {  include "polybot.name" . } }

   spec:
     containers:
       - name: polybot
         image: "{ {  .values.image.repository } }:{ {  .values.image.tag } }"
         imagePullPolicy: { {  .values.image.pullPolicy } }
         ports:
           - name: polybot
             containersPort: 8081
             protocol: TCP

