apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: {{ .Values.name }}
     tier: backend
 template:
   metadata:
     labels:
       app: {{ .Values.name }}
       tier: backend
   spec:
     volumes:
       - name: {{ .Values.volume.name }}
         persistentVolumeClaim:
           claimName: {{ .Values.volume.name }}
     containers:
       - name: {{ .Values.name }}
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
         volumeMounts:
           - mountPath: /usr/share/nginx/html
             name: {{ .Values.volume.name }}

         resources:
           limits:
             cpu: "1"
             memory: "100Mi"
           requests:
             cpu: "0.5"
             memory: "50Mi"

         livenessProbe:
          exec:
            command:
              - cat
              - /var/www/html/index.html
          initialDelaySeconds: 1
          periodSeconds: 5


