name:
  namespace: daria-jenkins
serviceaccount:
  name: jenkins-admin


RoleBinding:
  name: jenkins-role-binding
  subjects:
    name: jenkins-admin

role:
  name: jenkins

PersistentVolumeClaim:
    name: jenkinsagent-pvc
    accessModes:
      - ReadWriteOnce
    storage: 1Gi
