image:
  repository: dariakalugny/daria-repo
  tag: polybot
  pullPolicy: InfotPresent
name: polybot

volume:
  name: polybot-pvc

resources:
  limits:
    cpu: "1"
    memory: "100Mi"
  requests:
    cpu: "0.5"
    memory: "50Mi"