apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
     containers:
       - name: jenkins-server
         image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/daria-ecr-repo:jenkins-server
         resources:
           requests:
             memory: "100Mi"
           limits:
             memory: "200Mi"

         volumeMounts:
           - name: persistent-storage
             mountPath: /var/jenkins_home
         ports:
           - containerPort: 8080
     volumes:
       - name: persistent-storage
         persistentVolumeClaim:
           claimName: daria-ebs-pvc