apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
     volumes:
       - name: jenkins-server-pvc
         persistentVolumeClaim:
           claimName: jenkins-server-pvc

     containers:
       - name: jenkins-server
         image: jenkins/jenkins:lts-jdk11
         volumeMounts:
           - mountPath: "/var/lib/jenkins"
             name: jenkins-server-pv