apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
     volumes:
       - name: jenkins-server-pvc
         persistentVolumeClaim:
           claimName: jenkins-server-pvc
     containers:
       - name: jenkins-server
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
         volumeMounts:
           - mountPath: /home/var/lib/jenkins
             name: jenkins-server-pvc