apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app:  jenkins-server
     tier: backend
 template:
   metadata:
     labels:
       app:  jenkins-server
       tier: backend
   spec:
     volumes:
       - name: persistent-storage
         persistentVolumeClaim:
           claimName: efs-pvc

     containers:
       - name: jenkins-server
         image: 019273956931.dkr.ecr.eu-west-1.amazonaws.com/daria-ecr-repo:jenkins-server
         volumeMounts:
           - name: efs-volume
             mountPath: /var/jenkins_home

         ports:
           - containerPort: 8080
