apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-server-pvc
  hostPath:
    path: "/var/lib/jenkins"


spec:

  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 5Gi
