apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-server-pvc
spec:
  hostPath:
    path: "/var/lib/jenkins"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi