apiVersion: v1
kind: Service
metadata:
  name: jenkins-admin
  namespace: daria-jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080