apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: daria-jenkins
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
