apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: daria-jenkins
spec:
  selector:
    app: jenkins-server
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080