kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-storage
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: daria-efs-pv3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-storage
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0eed714f8cc045446
    volumeAttributes:
      encryptInTransit: "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daria-efs-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-storage
  resources:
    requests:
      storage: 5Gi