apiVersion: v1
kind: PersistentVolume
metadata:
  name: daria-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-storage
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05119cc562623261a

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daria-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-storage
  resources:
    requests:
      storage: 5Gi